export const MANUFACTURERS = [
  { value: 'DAEDONG', label: '대동' },
  { value: 'LS', label: 'LS' },
  { value: 'KUKJE', label: '국제' },
  { value: 'TYM', label: 'TYM' },
  { value: 'BRANSON', label: '브랜슨' },
  { value: 'DONGYANG', label: '동양' },
  { value: 'ASIA', label: '아시아' },
  { value: 'YANMAR', label: '얀마' },
  { value: 'ISEKI', label: '이세키' },
  { value: 'KUBOTA', label: '구보다' },
  { value: 'MITSUBISHI', label: '미쯔비시' },
  { value: 'HINOMOTO', label: '히노모토' },
  { value: 'SHIBAURA', label: '시바우라' },
  { value: 'JOHN_DEERE', label: '존디어' },
  { value: 'NEW_HOLLAND', label: '뉴홀랜드' },
  { value: 'MASSEY_FERGUSON', label: '매시퍼거슨' },
  { value: 'FENDT', label: '펜트' },
  { value: 'DEUTZ_FAHR', label: '도이츠파' },
  { value: 'SAME', label: '세메' },
  { value: 'LANDINI', label: '란디니' },
  { value: 'VALTRA', label: '발트라' },
  { value: 'CLAAS', label: '클라스' },
  { value: 'CASE_IH', label: '케이스IH' },
  { value: 'MAHINDRA', label: '마힌드라' },
  { value: 'KIOTI', label: '키오티' },
  { value: 'OTHER', label: '기타' }
]; 